apiVersion: v1
kind: Secret
metadata:
  name: azp-secret
type: Opaque
stringData:
  AZP_URL: https://dev.azure.com/sivabalaji280 
  AZP_TOKEN: 56BKNGHIvMnvcW83zYdpABZlLN2gowtJQ47TR0UVexDqEFW0JfA0JQQJ99CDACAAAAAAAAAAAAASAZDO45Eq 
  AZP_POOL: AKS-AGENT-POOL
type: Opaque